Module2 task1
htmlacademy-ecmascript/2049181-cinemaddict-18 pull request #4
Opened 2022-08-18 22:46 UTC by webgolub

2022-08-20 10:51 UTC, AlexMasterov requested changes

2022-08-20 10:51 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
<details>
<summary>model/films-model.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/model/films-model.js#L6
</details>

<details>
<summary>model/comments-model.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/model/comments-model.js#L17
</details>

get = (`film`) => {

Для подобных моделей неявно работает утиная типизация и при этом сигнатура их метод `get` различается, что нарушает [принцип подстановки Лисков](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8_%D0%91%D0%B0%D1%80%D0%B1%D0%B0%D1%80%D1%8B_%D0%9B%D0%B8%D1%81%D0%BA%D0%BE%D0%B2). Теперь нельзя _одинаковым_ образом работать с моделями.

2022-08-20 10:51 UTC, AlexMasterov commented on src/model/comments-model.js
> +    this.allComments = generateComments(this.filmsModel.get());
См. ТЗ:
> Комментарии _загружаются_ при открытии попапа

> GET `/comments/: film_id`
> Получение комментариев к фильму

После упрощения ТЗ для комментариев по сути не нужна модель, а достаточно возможности их загрузки по `movie.id`, что можно реализовать сервисом.

2022-08-20 10:51 UTC, AlexMasterov commented on src/presenter/main-presenter.js
<details>
<summary>presenter/main-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/presenter/main-presenter.js#L27-L31
</details>

[`Б 32`](https://up.htmlacademy.ru/ecmascript/18/criteries#b32)
> Своевременный выход из цикла: цикл не работает дольше, чем нужно

<details>
<summary>presenter/main-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/presenter/main-presenter.js#L33
</details>

this.mainFilmsListContainerComponent.getElement().`append`(...filmCardsViews)

[`Д 26`](https://up.htmlacademy.ru/ecmascript/18/criteries#d26)
> Операции над DOM-элементами инкапсулированы

Пожалуйста, просто сделай как [показано в примере демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-18/blob/module-2/src/presenter/board-presenter.js#L23-L25).

2022-08-20 10:51 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    render(new PopupBottomContainerView(this.films[0], this.commentsModel), this.popupInnerComponent.getElement());
2x `this.films[0]`

2022-08-20 10:51 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    render(new PopupBottomContainerView(this.films[0], this.commentsModel), this.popupInnerComponent.getElement());
new PopupBottomContainer`View`(this.films[0], `this.commentsModel`)

В MVP (= одна из основных тем интенсива) вью не должно напрямую работать с моделью. Для этого по умолчанию есть Презентер или другие абстракции, вроде сервисов.

2022-08-20 10:51 UTC, AlexMasterov commented on src/presenter/statistics-presenter.js
> +    render(new StatisticsView, statisticsContainer);
```diff
- render(new StatisticsView, statisticsContainer);
+ render(new StatisticsView(), container);
```

2022-08-20 10:51 UTC, AlexMasterov commented on src/util.js
> +export {
Все временные функции для генерации случайных данных перенести во временную директорию, чтобы потом их можно было удалить все разом.

> Это же советовал на JS1

2022-08-20 10:51 UTC, AlexMasterov commented on src/util.js
> +export {
Все функции для работы с датой перенеси в отдельную _под_ директорию, например `utils/date.js`.

2022-08-20 10:51 UTC, AlexMasterov commented on src/util.js
> +export {
<details>
<summary>util.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/util.js#L36-L38
</details>

const format`String`ToDate = (`string`) => dayjs(`string`).format('DD MMMM YYYY'); 
const formatString`To`DateForComment = (string) => dayjs(string).format('YYYY/MM/DD HH:MM');

Б9, Б10

<details>
<summary>util.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/util.js#L20
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/util.js#L22
</details>

Для именования функций форматирования даты просто используй один глагол `format` или `humanize` (как в демо проекте).

> На защите проекта могут придраться к `to` в название

2022-08-20 10:51 UTC, AlexMasterov commented on src/util.js
> +const minutesToHoursAndMinutes = (inputMInutes) => {
<details>
<summary>util.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/util.js#L22-L30
</details>

const `minutesTo`HoursAndMinutes = (inputM`I`nutes) => { 
  const minutes = inputMInutes % `60`; 
  const hours = Math.floor(inputMInutes / `60`); 
  const result = `(`hours`)` 

Б10, Б3, Б31

Плохое решение и сама реализация (= каскад нарушений).

Желательно переписать с использованием `dayjs`: [`Duration`](https://day.js.org/docs/ru/plugin/duration) + [`.format`](https://day.js.org/docs/ru/display/format), а также учесть другое замечание по именованию таких функций.

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +            <span class="film-card__comments">${handleCommentsCount(comments)}</span>
Работа функции `handleCommentsCount` не соответствует макету.

Нужно удалить.

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/main-film-card-view.js
>              <button class="film-card__controls-item film-card__controls-item--favorite" type="button">Mark as favorite</button>
См. ТЗ:
> В зависимости от состояния, некоторым элементам управления применяются соответствующие классы оформления. Например, активный фильтр и т. д. Примеры доступны в директории с вёрсткой (markup)

Нужно использовать значение из данных и CSS-класс из макета.

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
> +const renderComments = (comments) => comments.map(({author, date, comment, emotion}) =>
`renderComments`

Чем работа и результат этой функция отличается от `create`View`Template`?

> hint: она соблюдает единообразие в именование и кроме этого не "обманывает" своего пользователя

[`Б 10`](https://up.htmlacademy.ru/ecmascript/18/criteries#b10)
> Название функции или метода должно быть глаголом и **соответствовать действию, которое выполняет функция** или метод

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
> +  const commtentsToRender = comments.get(film);
const commtents`ToRender` = comments.get(film);

> `createViewTemplate` ничего не рендерит

[`Б 8`](https://up.htmlacademy.ru/ecmascript/18/criteries#b8)
> Массивы названы существительными во множественном числе

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
> +  const commtentsToRender = comments.get(film);
const `createViewTemplate` = (film, `comments) => {
  const commtentsToRender = `comments.get(film)`;

Что делает модель в обычной функции для создания шаблона с разметкой? 🤔

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
> +    this.comments = commentsModel;
this.`comments` = comments`Model`;

Лёгким движением руки брюки превращаются...

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-top-container-controls-view.js
> +export {createPopupControlsViewTemplate};
src/view/`popup-top-container-controls-view.js`

export {`createPopupControlsViewTemplate`};

[`Б 27`](https://up.htmlacademy.ru/ecmascript/18/criteries#b27) 

> Название модуля соответствует его содержимому

> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view.js`

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-top-container-controls-view.js
> +      <button type="button" class="film-details__control-button film-details__control-button--watchlist ${buttonHandle(watchlist)}" id="watchlist" name="watchlist">Add${textHandle(watchlist)} to watc
<details>
<summary>view/popup-top-container-controls-view.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/view/popup-top-container-controls-view.js#L2-L10
</details>

const `buttonHandle` = (button) => `(`(button)

Б10

Желательно удалить (и больше подобного не делать), а вместо них реализовать нечто подобное:

```js
createControlButtonTemplate('watched', 'Already watched', alreadyWatched)
```

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
> +          </tr>
Попробуй убрать дублирование, реализуя нечто подобное:

```js
createTableTemplate('Director', director)
```

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
> +const generateGenreList = (genres) => genres.map((genreItem) =>
const `generate`GenreList = (genres) => genres.map((genreItem) =>

[`Б 10`](https://up.htmlacademy.ru/ecmascript/18/criteries#b10)
> Название функции или метода должно быть глаголом и **соответствовать действию, которое выполняет функция** или метод

2022-08-20 10:51 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
> +
<details>
<summary>view/popup-top-container-view.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/2c084041ae42bc34e5f01ad00e984572a6b4d82b/src/view/popup-top-container-view.js#L5-L15
</details>

const `generate`WritersTitle = (writers) => `(writers.length > 1)`

> Опять эти `()` в условиях 🤔 

[`Б 10`](https://up.htmlacademy.ru/ecmascript/18/criteries#b10)
> Название функции или метода должно быть глаголом и **соответствовать действию, которое выполняет функция** или метод

[`Д 11`](https://up.htmlacademy.ru/ecmascript/18/criteries#d11)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий

ТЗ этого не требует, но если хочешь, то лучше реализуй нечто более универсальное, например:

```js
pluralize(genres, 'Genre', Genres')
```

2022-08-20 12:51 UTC, AlexMasterov commented on src/moc/comment.js
> +
src/`moc`/comment.js

1. Вероятно, должно быть `mock`
2. Данные и функции, которые их возвращают неправильно называть "моками"

<details>
<summary>Это не моки</summary>

![image](https://user-images.githubusercontent.com/700213/185746967-afa1ae22-5d5a-453b-ba9f-4474a591f49b.png)
</details>

2022-08-20 13:10 UTC, webgolub commented on src/moc/comment.js
> +  date: generateRandomDate(),
Формат ISO для даты я использовал потому что в [ТЗ](https://up.htmlacademy.ru/profession/react/10/ecmascript/18/project/cinemaddict) приведена структура данных Movie, в которой даты именно в этом формате. Так же на ретро разбирали чей-то проект и там так же используется этот формат. И разбирались функции на основе dayjs для форматирования даты в нужный формат. Я сделал предположение что и с сервера данные будут приходить в таком же формате.
Честно говоря, теперь, конечно, не уверен в правильности выбора.

2022-08-20 13:14 UTC, AlexMasterov commented on src/moc/comment.js
> +  date: generateRandomDate(),
В ТЗ структуры данных с сервера показаны в формате `JSON`, который используется для _сериализации_. Но в приложение нужно использовать структуры и типы самого языка.

> [Сериализация](https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F) используется для передачи объектов [из памяти] по сети и для сохранения их в файлы

> [JSON](https://ru.wikipedia.org/wiki/JSON) — текстовый формат _обмена_ данными

> [`ISO` 8601](https://ru.wikipedia.org/wiki/ISO_8601) используется для сериализации [объекта] даты

2022-08-20 13:19 UTC, AlexMasterov commented on src/moc/comment.js
> +  date: generateRandomDate(),
> Честно говоря, теперь, конечно, не уверен в правильности выбор

См. [Парсите, а не валидируйте](https://habr.com/ru/post/498042/#:~:text=%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%20%D0%BD%D0%B5%20%D1%81%D0%BA%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D0%B8%D1%80%D1%83%D0%B5%D1%82%D1%81%D1%8F.-,%D0%9E%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8,-%D0%9D%D0%B0%D0%B4%D0%B5%D1%8E%D1%81%D1%8C%2C%20%D0%BA%20%D1%8D%D1%82%D0%BE%D0%BC%D1%83)
> программа, которая не парсит заранее все необходимые ей данные, рискует обработать часть данных, затем обнаружить ошибку в другой части, и внезапно оказаться в ситуации, когда нужно откатить уже произведённые изменения, чтобы сохранить консистентность

> Парсинг избегает этой проблемы, разделяя программу на две фазы: _фазу парсинга_ и _фазу исполнения_, где ошибка, связанная с неверными входными данными, может произойти только в первой фазе

> Переведите ваши данные в наиболее точное представление так рано, как это возможно. В идеале, это должно происходить на границе вашей системы, до того, как _любые_ данные начали обрабатываться

2022-08-20 13:21 UTC, webgolub commented on src/model/comments-model.js
> +  get = (film) => {
В одном из скринкастов или на ретро (могу путать где именно) было сказано что сейчас можно использовать такой способ получения данных, а потом его перепишем на геттер. Просто в спешке бездумно содрал с ретро, скорее всего, хотя согласен что можно было написать get(film) {}

2022-08-20 13:22 UTC, AlexMasterov commented on src/moc/comment.js
> +  date: generateRandomDate(),
> Переведите ваши данные в наиболее точное представление так рано, как это возможно. В идеале, **это должно происходить на границе вашей системы, до того, как любые данные начали обрабатываться**

См. [примере итоговой версии демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-18/blob/module-8/src/model/tasks-model.js#L84).

2022-08-20 13:31 UTC, AlexMasterov commented on src/moc/comment.js
> +  date: generateRandomDate(),
> Так же на ретро разбирали чей-то проект и там так же используется этот формат

Например, в проекте Большое путешествие есть сортировка по продолжительности. Ты понимаешь, что для её работы потребуется каждый раз _парсить_ по две даты из каждого объекта, чтобы их сравнить. Чтобы отобразить дату в нужном формате её снова сначала потребуется распарсить и превратить в объекта, чтобы примениит форматирование. И так каждый раз, снова и снова.

Это безумие.

2022-08-20 13:34 UTC, webgolub commented on src/model/comments-model.js
> +  get = (film) => {
Я без подсказок с ретро вообще не мог понять как связать комментарии с фильмом. Никак не получается разобраться, я и эту реализацию с трудом в голове держу. Подскажи, как можно реализовать получения всех комментов для одного фильма, если метод get() сделать без параметра, чтобы сигнатура методов в разных моделях совпадала? 
Получать от модели архив всех комментариев и вне модели (например, в презентере) уже заводить функцию, которая будет получать из этого архива комментарии для нужного фильма - такой вариант не нарушит какой-то из принципов?

2022-08-20 13:39 UTC, webgolub commented on src/model/comments-model.js
> +    this.allComments = generateComments(this.filmsModel.get());
Я ещё не знаю что такое сервис, об этом будет позже, судя по тому что упоминали на  ретро. Я путаюсь в терминах: в задании прописано что для комментариев обязательно нужно заводить отдельную структуру данных, а как мне получать доступ к данным комментариев без модели?

2022-08-20 13:40 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
При таком объявление "методы" будут own enumerable и не попадут в прототип, т.е. будут создаваться по новой для каждого экземпляра.

Объявить метод стрелкой уместно, если он может быть вызван вне [контекста] объекта класса, например, как обработчик событий DOM. В случае такого объявления контекст объекта будет сохранен и его не потребуется привыязывать явно.

Авторы курса написали, что в будущих потоках откажутся от повсеместных стрелок, потому что это вводит путаницу.

2022-08-20 13:42 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
> потом его перепишем на геттер

Тогда постарайся учесть [`Д 8`](https://up.htmlacademy.ru/ecmascript/18/criteries#d8):
> Методы внутри классов упорядочены

2022-08-20 13:49 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
В другом замечание пояснил, что связывать комментарии с фильмами больше не требуется. Вместо этого потребуется при _каждом_ открытии попапа загружать комментарии к фильму с сервера, которые вернет готовый массив, где даже их порядок будет совпадать с порядком их `id` в `movies.comments` 😃

> Подскажи, как можно реализовать получения всех комментов для одного фильма, если метод get() сделать без параметра, чтобы сигнатура методов в разных моделях совпадала?

`getByFilmId`?

2022-08-20 13:55 UTC, AlexMasterov commented on src/model/comments-model.js
> +    this.allComments = generateComments(this.filmsModel.get());
См. https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/4#discussion_r950697853.

Требование задания давно неактуально для текущего ТЗ, которое упростили.

2022-08-20 13:56 UTC, webgolub commented on src/presenter/main-presenter.js
Да, теперь я вижу что пример с циклами из критериев прямо то что я сделал, только наоборот.
Про инкапсуляцию тоже теперь вроде понятно, но таким образом я пытался избежать работы с элементом, который уже добавлен в DOM. Выходит, это можно делать в данном случае? Я запутался.

2022-08-20 14:04 UTC, AlexMasterov commented on src/presenter/main-presenter.js
Прямая работа с элементом компонента нарушает его инкапсуляцию, но в этом случае это не так критично.

> В нашем случае утилитарные функции фреймворка — исключение

2022-08-20 14:06 UTC, AlexMasterov commented on src/presenter/main-presenter.js
На этом интенсиве заниматься оптимизациями работы с DOM не нужно. Просто используй функцию `render`. 

> Для оптимизации следует доработать саму функцию `render`, что произойдет далее или еще одну

2022-08-20 14:14 UTC, AlexMasterov commented on src/model/comments-model.js
> +    this.allComments = generateComments(this.filmsModel.get());
В другом проекте связывание данных между структурами актуально + вью, даже тупой, при изменении типа или направления нужна возможность получить соответствующий список предложений и описание направления. Чтобы не передавать модель во вью, нарушая MVP и заставляя саму вью "знать" структуру данных, их способ связывания, реализовывать для этого код и т.п., лучше запихнуть модели в еще одну абстракцию, которую можно называть сервисом с методами для получения этих данных.

2022-08-20 14:21 UTC, webgolub commented on src/presenter/popup-presenter.js
> +    render(new PopupBottomContainerView(this.films[0], this.commentsModel), this.popupInnerComponent.getElement());
Ну это же временное решение. Получается нужно завести под него какую нибудь const filmForPopup = this.films[0]?

2022-08-20 14:24 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    render(new PopupBottomContainerView(this.films[0], this.commentsModel), this.popupInnerComponent.getElement());
Да.

Не забывай, что получение элемента из массива имеет свою стоимость.

2022-08-20 14:27 UTC, webgolub commented on src/presenter/popup-presenter.js
> +    render(new PopupBottomContainerView(this.films[0], this.commentsModel), this.popupInnerComponent.getElement());
Здесь не понятно. Вроде же вью не напрямую работает с моделью, а получает извне данные, которые я передаю в презентере. Как тогда иначе реализовать передачу данных для отрисовки во вью?

2022-08-20 14:30 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +    render(new PopupBottomContainerView(this.films[0], this.commentsModel), this.popupInnerComponent.getElement());
В простом случае достаточно передавать в конструктор уже готовый _массив_ с комментариями, а в более сложном реализовать метод для добавления комментариев (ведь для их загрузки нужно время, а попап можно показать без них).

2022-08-20 14:40 UTC, webgolub commented on src/util.js
> +export {
Да, я помню про совет. Дело в том что в данный момент я не уверен какие функции понадобятся при работе с «боевыми» данными.

2022-08-20 14:44 UTC, webgolub commented on src/util.js
> +export {
Опять же я пока не знаю какие функции мне понадобятся после перехода с моковых на настоящие данные, поэтому сложно сейчас распланировать файл(ы) util.js

2022-08-21 00:32 UTC, webgolub commented on src/view/main-film-card-view.js
> +            <span class="film-card__comments">${handleCommentsCount(comments)}</span>
Правильно ли я  понял что нужно сделать так:
` <span class="film-card__comments">${comments.length} comments</span>`

2022-08-21 01:52 UTC, webgolub commented on src/view/popup-bottom-container-view.js
> +  const commtentsToRender = comments.get(film);
Я помню что мы уже это обсуждали на JS1, но с ходу не смог найти. Как мне помнится, ты писал что могут придраться к тому что вторая часть названия переменной не во множественном числе, несмотря на то что первая часть comment`s` - верно? Как в таком случае можно назвать переменную?

2022-08-21 01:53 UTC, webgolub commented on src/view/popup-bottom-container-view.js
> +  const commtentsToRender = comments.get(film);
Да, из предыдущих комментов понял что протащил модель туда, где её быть не должно.

2022-08-21 01:55 UTC, webgolub commented on src/view/popup-bottom-container-view.js
> +    this.comments = commentsModel;
Помимо того что модели тут быть не должно, я ещё просто записал её в переменную, название которой подразумевает массив и путает, верно?

2022-08-21 02:03 UTC, webgolub commented on src/view/popup-top-container-controls-view.js
> +export {createPopupControlsViewTemplate};
Я решил немного разгрузить вью, в которой использую функцию из этого модуля, следуя совету из ретро, но до конца не разобрался. Теперь вижу проблему. 
Посоветуй как лучше поступить, пожалуйста:
1) Назвать этот модуль без суффикса `view` и импортировать в нужную вью?
2) Удалить отдельный модуль и перенести его код в модуль со вью? 
3) Или  сделать из модуля полноценную вью и отрисовывать её в презентере?

2022-08-21 02:56 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +            <span class="film-card__comments">${handleCommentsCount(comments)}</span>
Да.

2022-08-21 02:59 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
> +  const commtentsToRender = comments.get(film);
Массив `comments`.

В этой функции (и во вью) не должно быть прямой работы с моделью. Нужно убрать модель из зависимостей вью, а передавать в конструктор сразу готовый массив. См. https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/4#discussion_r950680645.

2022-08-21 03:00 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
> +    this.comments = commentsModel;
Да.

2022-08-21 03:02 UTC, AlexMasterov commented on src/view/popup-top-container-controls-view.js
> +export {createPopupControlsViewTemplate};
2.

Для 1 и 3 сначала используй консультацию.

2022-08-21 10:51 UTC, webgolub commented on src/view/popup-top-container-controls-view.js
> +export {createPopupControlsViewTemplate};
Пока сделаю 2, но сделаю себе пометку что нужно будет на консультации этот вопрос обсудить, спасибо.

2022-08-21 11:10 UTC, webgolub commented on src/view/popup-top-container-view.js
> +
Я эти `()` в условия добавлял по совету с ретро, мол так нагляднее выглядит условие в тернарном операторе.
Не нужно так делать? 😳

2022-08-21 11:20 UTC, webgolub commented on src/moc/comment.js
> +
Спасибо что указал. 
Конечно, я опечатался в слове `mock`. Как выяснилось, это и не mock вовсе.

Я погуглил различия, в материалах в основном касаются тестирования и мне пока что сложно въехать.
Допустимо ли назвать директорию `stub` или может `fish` будет лучше?

2022-08-21 11:39 UTC, webgolub commented on src/moc/comment.js
> +  date: generateRandomDate(),
Спасибо за развёрнутое объяснение, буду изучать.

2022-08-21 12:02 UTC, webgolub commented on src/moc/comment.js
> +  date: generateRandomDate(),
Правильно ли я понял, что в моём случае, нужно оставить генерацию «рыбного фильма» как есть, с датой в формате ISO, и в `films-model.js ` перед возвращением массива фильмов, пройтись по нему и привести даты в формат Date?
Такой способ будет приближенным к работе с реальными данными с сервера, как я понимаю.

Или нужно сразу в генерации «рыбного фильма» использовать функции, которые генерируют дату в виде объекта Date?

2022-08-21 12:06 UTC, AlexMasterov commented on src/moc/comment.js
> +  date: generateRandomDate(),
Можешь сразу использовать вариант "данных, после парсинга", где дата представлена объектом `Date` или `dayjs`.

2022-08-21 12:18 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
> +
Конкретно в этом простом условие условие это воспринимается, как _визуальный_ шум.

Скорее всего на ретро имелись ввиду более сложные условие и места, где `()` используется для переноса строки и лучшего форматирования. (т.е. не по назначению). Посмотрю сам.

2022-08-21 12:23 UTC, AlexMasterov commented on src/moc/comment.js
> +
Советую не использовать терминологию тестирования, а просто назвать `data`.

Проблема с путаницей куда серьёзней, чем ты думаешь 😃

2022-08-21 12:31 UTC, webgolub commented on src/model/comments-model.js
> +  get = (film) => {
Правильно я понимаю, что allComments в «боевом» применении будет получать от модели массив всех комментариев, которые модель будет получать с сервера при каждом обращении к методу `getByFilm(film)`?
У меня сейчас почти так же, но allComments «получает» массив всех комментариев один раз при инициализации.

Вопрос по поводу методов объектов и вью. 
Методы вью в проекте сделаны одинаковыми для всех вью, чтобы у них был одинаковый интерфейс и это пригодится чуть позже, когда мы будем изучать наследование, как я понял.
А если я заведу метод `getByFilm()` у модели `CommentsModel`, то получится что её интерфейс будет различаться с интерфейсом `FilmsModel`, хотя я изначально думал что он должен быть одинаковым, по аналогии с вьюхами. 
Получается, не нужно стремиться к унификации интерфейса одной сущности? В терминах путаюсь - разные модели это одна сущность же? В общем, каша в голове.

2022-08-21 12:36 UTC, webgolub commented on src/moc/comment.js
> +
Ох, я вообще ощущаю себя как на минном поле: чуть влево-вправо качнулся и... 
Одна надежда, что в будущем получится разгрести всю эту новую информацию по полочкам и будет уже не так страшно (сложно) 😲

2022-08-22 10:21 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
Сейчас могу ответить кратко.


<details>
<summary>model/films-model.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/c03180acb7511383bbaf08f035e91453610613e8/src/model/films-model.js#L3-L7
</details>

Советую оставить одну модель для фильмов, а для получения/загрузки комментариев к фильму прямо _в ней_ добавить метод: (потом он будет загружать комментарии с сервера)

```js
// fetchComments / loadComments
getComments(film) {
  const allComments = generateComments(this.films);
  return film.comments
    .map((commentId) => allComments.find((comment) => comment.id === commentId)); 
}
```

2022-08-22 10:27 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
> У меня сейчас почти так же, но allComments «получает» массив всех комментариев один раз при инициализации

См. внимательно https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/4#discussion_r950677635.

В прошлом ТЗ это было нужно, чтобы реализовать дополнительный пункт ТЗ (необязательный), который назывался `Offline`. Приложение должно было работать в отсутствие сети, используя `Service Worker`. Повторю, что в актуальном ТЗ этот пункт убрали и поэтому загружать все комментарии больше не требуется.

2022-08-22 10:33 UTC, AlexMasterov commented on src/model/comments-model.js
> +  get = (film) => {
Сейчас могу ответить кратко.


<details>
<summary>model/films-model.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/c03180acb7511383bbaf08f035e91453610613e8/src/model/films-model.js#L3-L7
</details>

Советую оставить только одну модель для фильмов, а для получения/загрузки комментариев к фильму прямо _в ней_ добавить метод: (потом он будет загружать комментарии с сервера)

```js
// fetchComments / loadComments
getComments(film) {
  const allComments = generateComments(this.films);
  return film.comments
    .map((commentId) => allComments.find((comment) => comment.id === commentId)); 
}
```

2022-08-23 09:38 UTC, merged

2022-08-23 10:30 UTC, AlexMasterov commented on src/view/statistics-view.js
> +    this.filmsModel = filmsModel;
См.:
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/4#discussion_r950678629
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/4#discussion_r950680645