Module3 task1
htmlacademy-ecmascript/2049181-cinemaddict-18 pull request #5
Opened 2022-08-24 14:34 UTC by webgolub

2022-08-24 15:03 UTC, AlexMasterov requested changes

2022-08-25 01:39 UTC, webgolub commented on src/presenter/main-presenter.js
> +      document.body.querySelector('.film-details').remove();
Если удалить строчку
`document.body.querySelector('.film-details').remove();`
То попап не исчезает при закрытии. Я не могу разобраться почему, ведь я «зануляю» его верхний компонент - разве этого не достаточно чтобы он пропал из DOM?

2022-08-25 01:53 UTC, webgolub commented on src/view/statistics-view.js
> +    this.#films = films;
Правильно ли я понял, что можно передать количество фильмов так:
`render(new StatisticsView(this.#filmsModel.films.length), container);`

2022-08-25 01:54 UTC, webgolub commented on src/presenter/popup-presenter.js
> +      .addEventListener('click', closeButtonClickCallback);
В разборе демо-проекта говорится о том что потом будет переделано. Сделал по аналогии.

2022-08-25 06:43 UTC, AlexMasterov commented on src/presenter/main-presenter.js
> +      document.body.querySelector('.film-details').remove();
> Если в popupPresenter.clear() добавить this.#popupSectionComponent.element.remove(); — такое решение допустимо же?

Так и следовало сделать.

2022-08-25 06:43 UTC, AlexMasterov commented on src/view/statistics-view.js
> +    this.#films = films;
Так лучше.

2022-08-25 11:04 UTC, merged