Module4 task1
htmlacademy-ecmascript/2049181-cinemaddict-18 pull request #7
Opened 2022-08-28 12:45 UTC by webgolub

2022-08-28 15:18 UTC, AlexMasterov requested changes

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/main-films-section-view.js
>  const createViewTemplate = () => '<section class="films"></section>';
Создание вью можно попробовать упростить с помощью фабрики.

<details>
<summary>Пример</summary>

```js
// framework/view/abstract-view-factory.js
import AbstractView from './abstract-view.js';

const createView = (createTemplate) => class extends AbstractView {
  constructor(state) {
    super();

    this._state = { ...state };
  }

  get template() {
    return createTemplate(this._state);
  }
}

export {
  createView,
};
```
```js
// view/main-films-section-view.js
import { createView } from './framework/view/abstract-view-factory.js';

export default createView(() => (
  '<section class="films"></section>'
));
```
Можно также использовать с параметрами:

```js
const createViewTemplate = ({ text, isHidden = false }) => { ... }
```
```js
MainFilmsListView({ text: 'All movies. Upcoming', isHidden: true })
```
</details>

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/popup-inner-view.js
> +  setClickHandler = (callback) => {
Этот метод устанавливает обработчик для кнопки закрытия и поэтому должен называться соотвествующие.

Б10

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/popup-inner-view.js
> +      .addEventListener('click', this.#clickHandler);
this.element.querySelector('.film-details__`close-btn`').addEventListener('click', this.#`clickHandler`);

Д4

> После исправления нужно не забыть исправить название коллбэка + в нем учесть Б10

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
>  const createGenreList = (genres) => genres.map((genreItem) =>
См. https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/4#discussion_r950680240.


Б10

```diff
- const createGenreList = (genres) => genres.map((genreItem) =>
+ const createGenreListTemplate = (genres) => genres.map((genre) =>
```

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/view/popup-top-container-view.js#L8

В `utils`.

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/popup-top-container-view.js
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/view/popup-top-container-view.js#L13-L15


Лучше не делать подобной логики внутри таких функций.

Лучше явно:
```js
${createTableRowTemplate(pluralize(writers, 'Writer', 'Writers'), writers.join(', '))}
```

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/statistics-view.js
>  const createViewTemplate = (filmsCount) => `<p>${new Intl.NumberFormat('us-US').format(filmsCount)} movies inside</p>`;
```js
// utils
const formatFilmCount = new Intl.NumberFormat('us-US').format;
````
```js
`<p>${formatFilmCount(filmsCount)} movies inside</p>`
```

> Вью создается один раз — поэтому некритично

2022-08-28 15:18 UTC, AlexMasterov commented on src/view/statistics-view.js
>      this.#filmsCount = filmsCount;
```js
typeof filmsCount // number
```

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/view/statistics-view.js#L6

#filmsCount = `null`;

См. https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/pull/6#discussion_r955018641.

2022-08-28 15:18 UTC, AlexMasterov commented on src/presenter/main-presenter.js
<details>
<summary>framework/render.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/framework/render.js#L17
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/framework/render.js#L51-L52
</details>

`Element`

Б6

Думаю, что в случае `framework` некритично.

2022-08-28 15:18 UTC, AlexMasterov commented on src/presenter/main-presenter.js
<details>
<summary>framework/view/abstract-view.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/framework/view/abstract-view.js#L15
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/framework/view/abstract-view.js#L48-L49
</details>

<details>
<summary>framework/view/abstract-view.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/framework/view/abstract-view.js#L31
</details>

```diff
- if (!this.#element) { 
+ if (this.#element === null) { 
```

2022-08-28 15:25 UTC, AlexMasterov commented on src/presenter/main-presenter.js
См. ТЗ:
> Клик по карточке фильма (**за исключением кликов по кнопкам управления**) открывает попап с подробной информацией о фильме

В этом задание можно добавить пустые обработчики для клика по кнопкам, а в след. добавить обработку самому клика.

2022-08-28 15:28 UTC, AlexMasterov commented on src/presenter/main-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/187081814-b90a4d8c-edb3-4748-93e7-018b2a697a52.png)

</details>

При клике на карточку:
1. уже открытый попап переоткрывается, что неэфективно;
2. его разметка с комментариями дублируется.


Второе нужно исправить обязательно.

2022-08-28 15:30 UTC, AlexMasterov commented on src/view/popup-bottom-container-view.js
<details>
<summary>view/popup-bottom-container-view.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/view/popup-bottom-container-view.js#L36-L54
</details>

Разметка для эмоций дублируется.

2022-08-28 15:35 UTC, AlexMasterov commented on src/presenter/main-presenter.js
<details>
<summary>presenter/main-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/presenter/main-presenter.js#L65-L66
</details>

Здесь сначала устанавливается обработчик, а потом рендерится.

<details>
<summary>presenter/main-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/presenter/main-presenter.js#L83-L84
</details>

Здесь уже сначала рендерится, а потом устанавливается обработчик 🤔

2022-08-28 15:36 UTC, AlexMasterov commented on src/presenter/main-presenter.js
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/presenter/main-presenter.js#L96-L97

Теперь лучше использовать `remove`: (см. примеры демо проекта)
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/framework/render.js#L67

2022-08-28 15:41 UTC, AlexMasterov commented on src/presenter/main-presenter.js
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/presenter/main-presenter.js#L50-L51
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/presenter/main-presenter.js#L56-L57

Удаление обработчика дублируется.

2022-08-28 15:44 UTC, AlexMasterov commented on src/presenter/main-presenter.js
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/5d7c56f5bc84dccd081f2941cfc701c7088a5d2b/src/model/films-model.js#L7

Желательно подправить форматирование.

2022-08-29 01:03 UTC, webgolub commented on src/view/main-films-list-view.js
> +    : '';
Увидел что лишаю View универсальности, привязывая к данным ТЗ. Понял что можно передать флаг «скрытности» параметром в конструктор.
Но вот завис, пытаясь понять `{ isHidden = false } = {}` — не пойму как можно использовать эту запись.

2022-08-29 01:19 UTC, webgolub commented on src/view/main-films-list-view.js
> +    : '';
И ещё. Вот такой у меня получился класс:
```js
export default class MainFilmsListView extends AbstractView {
  #text = '';
  #isHidden = false;

  constructor(text, isHidden = false) {
    super();
    this.#text = text;
    this.#isHidden = isHidden;
  }

  get template() {
    return createViewTemplate(this.#text, this.#isHidden);
  }
}
```
Тут при объявлении я использую `#isHidden = false` и значение по умолчанию в конструкторе тоже `isHidden = false`. Смущает что дублируется одно и то же, но объявлять как null не логично при том что я хочу значение по умолчанию и если из параметра убрать значение по умолчанию - так можно или могут быть проблемы?

2022-08-29 01:31 UTC, webgolub commented on src/view/main-films-list-view.js
> +export default class MainFilmsListEmptyView extends AbstractView {
Не могу понять почему всё работает и не выдаёт никакой ошибки, независимо от того как я называю класс в этой строчке.
При том, что при импорте в mainPresenter я пишу:
import MainFilmsListView from '../view/main-films-list-view.js';

2022-08-29 01:58 UTC, webgolub commented on src/view/popup-inner-view.js
> +      .addEventListener('click', this.#clickHandler);
Название обработчика исправил на `#closeButtonclickHandler`
А что из Б10 нужно в нём учесть, он ведь обработчик события DOM и назван по маске *handler?

2022-08-29 03:06 UTC, AlexMasterov commented on src/view/main-films-list-view.js
> +    : '';
> Но вот завис, пытаясь понять `{ isHidden = false } = {}` — не пойму как можно использовать эту запись

Если вместо этого:
```js
MainFilmsListView('All movies. Upcoming', true)
````

захочешь такой интерфейс:

```js
MainFilmsListView('All movies. Upcoming')
MainFilmsListView('All movies. Upcoming', { isHidden: true })
```
тогда:
```js
constructor(text, { isHidden = false } = {}) {
```

2022-08-29 03:10 UTC, AlexMasterov commented on src/view/main-films-list-view.js
> +export default class MainFilmsListEmptyView extends AbstractView {
Так работает экспорт `default` и поэтому у него много противников. 
Из-за этого авторы курса давно обсуждали переход на именованный экспорт.

2022-08-29 03:45 UTC, AlexMasterov commented on src/view/popup-inner-view.js
> +      .addEventListener('click', this.#clickHandler);
this._callback.`click`

Здесь название коллбэка — это _метод_ объекта, а значит его название должно начинаться с глагола, чтобы учитывать Б10. В демо проекте это не соблюдается, но ты постарайся учесть, потому что на защите могут придраться.

2022-08-31 17:49 UTC, webgolub commented on src/presenter/main-presenter.js
Не могу уловить что тут не так. Б6 же про названия классов, а это переменные внутри функций.

2022-08-31 17:57 UTC, webgolub commented on src/presenter/main-presenter.js
Тут смысл чтобы было нагляднее, когда мы знаем что в свойстве может быть только null при отсутствии элемента?
Или есть какая-то разница в исполнении между этими двумя записями (например, в затрате ресурсов на проверку)?

2022-08-31 20:16 UTC, webgolub commented on src/view/main-films-section-view.js
>  const createViewTemplate = () => '<section class="films"></section>';
Пока не могу до конца въехать в некоторые детали  работы этой фабрики, можно ли оставить реализацию простых вью через неё на потом? Спасибо за разбор такого способа!

2022-08-31 20:39 UTC, AlexMasterov commented on src/const.js
> +  FAVORITE: '.film-card__controls-item--favorite'
> Почему подобное находится в _общем_ модуле `const` 🤔

Это лишние + относиться к деталями реализации одного компонента.

2022-08-31 20:39 UTC, AlexMasterov commented on src/presenter/main-presenter.js
> +      document.removeEventListener('keydown', handlerName);
Плохое решение, которое вдобавок нарушает критерии.

Далее потребуется переделать.

2022-08-31 20:39 UTC, AlexMasterov commented on src/presenter/popup-presenter.js
> +  init(film, HandleCloseButtonClick) {
init(film, `H`andleCloseButtonClick) {

[`Б 3`](https://up.htmlacademy.ru/ecmascript/18/criteries#b3)
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2022-08-31 20:39 UTC, AlexMasterov commented on src/util.js
> +const isNotControlButton = (evt) => !evt.target.className.includes (CONTROL_BUTTONS_CLASS);
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/07cad05aaa4aac6a638784de6ce688e779cb3197/src/util.js#L8-L10
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/07cad05aaa4aac6a638784de6ce688e779cb3197/src/util.js#L14-L16

Всё это относится к одному компоненту и не может быть (пере)использовано в рамках всего проекта, как некий общий код.

> `util.js` ожидаемо превращается в помойку

2022-08-31 20:39 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
На этом интенсиве подобные решения неуместны.

Далее желательно переделать без прямой работы с `document`.

2022-08-31 20:39 UTC, AlexMasterov commented on src/view/main-films-list-view.js
> +  const handleHiddenClass = (hiddenFlag) => hiddenFlag
const `handle`HiddenClass = (hidden`Flag`) => hidden`Flag`

Снова эти плохие названия, не смотря на мои примеры 🤔

2022-08-31 20:41 UTC, AlexMasterov commented on src/presenter/main-presenter.js
См. Б6:
> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

2022-08-31 20:45 UTC, AlexMasterov commented on src/presenter/main-presenter.js
Да, можно сказать, что так нагляднее и безопасней.

> По итогу, в машинном коде логическая проверка будет работать немного быстрее проверки на значение, поскольку требует одной операции с битами вместо двух

2022-08-31 20:46 UTC, merged

2022-08-31 20:49 UTC, AlexMasterov commented on src/view/main-films-section-view.js
>  const createViewTemplate = () => '<section class="films"></section>';
У меня есть варианты расширения классов фреймоврка, которые позволяют удобно работать с доч. компонентами, без их ручной сборки и т.п. Как некий заход и подготовка к React. Но сейчас подобное может оказать непосильным 😃

2022-08-31 21:29 UTC, webgolub commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
Намекни куда копать в сторону нормального решения, пожалуйста

2022-08-31 21:39 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
<details>
<summary>presenter/popup-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/dad8076c30843ea522659fe92c79f3d6887d0fd5/src/presenter/popup-presenter.js#L8-L9
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/dad8076c30843ea522659fe92c79f3d6887d0fd5/src/presenter/popup-presenter.js#L32-L33
</details>

У тебя даже сейчас есть на что завязаться, без добавления флагов и состояния открытия:
```js
isOpen() {
  return this.#film !== null;
}
```

2022-08-31 21:44 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
https://github.com/htmlacademy-ecmascript/2049181-cinemaddict-18/blob/dad8076c30843ea522659fe92c79f3d6887d0fd5/src/view/main-film-card-view.js#L104-L105

Подобной проверки во вью вообще быть не должно.

2022-08-31 21:57 UTC, webgolub commented on src/view/main-films-list-view.js
> +  const handleHiddenClass = (hiddenFlag) => hiddenFlag
`handle` нельзя использовать - не знаю как ещё назвать действие по добавлению/не добавлению класса?
Не придумал как назвать параметр, при том что isHidden я использую уровнем выше.

Да и такой же нейминг у меня в другом модуле - main-film-card-view.js 
```js
const createControlButtonTemplate = ( id, text, isActive = false ) => {
  const handleActiveClass = (activeFlag) => activeFlag
    ? 'film-card__controls-item--active'
    : '';

  return `<button class="film-card__controls-item film-card__controls-item--${id} ${handleActiveClass(isActive)}" type="button">${text}</button>`;
};
```
Там тоже нужно переделать?

2022-09-01 13:16 UTC, webgolub commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
Во вью не должно быть абсолютно никакой логики, касательно обработчиков событий, только навешивание обработчика на элемент и всё - верно?

2022-09-01 16:57 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
В твоем решение проверку на `isNotControlButton` можешь оставить.

> В других обработчиков для кнопок можно попробовать остановить распространение событий

`isNoPopupOpened` замени на `PopupPresenter.isOpen` и вызывай на уровне презентера списков, в `handleFilmComponentClick`.

2022-09-01 17:03 UTC, AlexMasterov commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
> Можно ли во вью так передавать объект события в коллбэк-обработчик клика?

В таком случае лучше на уровне `cardClickHandler` выбрать из объекта событий нужное и передать в коллбэк готовым (обработанным), как полезную нагрузку. Например, в _крайне неудачном примере_ лучше сделать так:

```js
this._callback.handleCardClick({ isNotControlButton: isNotControlButton() });
```

2022-09-02 00:20 UTC, webgolub commented on src/view/main-film-card-view.js
> +    if (isNotControlButton(evt) && isNoPopupOpened()) {
Кажется разобрался, с трудом пока что понимаю на каком уровне что должно делаться, как разделять зависимости компонентов друг от друга. Вот ты объяснил и вроде всё логично, но самому в процессе планирования и написания сложно всё правильно «распределить» по модулям, вот и получается то что получается (паутина хвостов из одного модуля в другой).

2022-09-02 00:25 UTC, webgolub commented on src/presenter/main-presenter.js
> +      document.removeEventListener('keydown', handlerName);
Беру на заметку, пока что оставлю как есть.